import { GeneratedContract, SecurityReport, PlacedBlock, GasEstimates } from '../types';

interface ContractNode {
  id: string;
  type?: string;
  position: { x: number; y: number };
  data: PlacedBlock;
}

// Template for generating Solidity contracts
const CONTRACT_TEMPLATE = `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

{{imports}}

/**
 * @title {{contractName}}
 * @dev Generated by ContractForge - No-Code Smart Contract Builder
 * @notice This contract was auto-generated. Please review before deployment.
 */
contract {{contractName}} {{inheritance}} {
    {{stateVariables}}

    {{events}}

    {{modifiers}}

    {{constructor}}

    {{functions}}
}
`;

interface ProcessedBlock {
  imports: Set<string>;
  inheritance: Set<string>;
  stateVariables: string[];
  events: string[];
  modifiers: string[];
  constructorCode: string[];
  functions: string[];
}

function processBlocks(nodes: ContractNode[]): ProcessedBlock {
  const result: ProcessedBlock = {
    imports: new Set(),
    inheritance: new Set(),
    stateVariables: [],
    events: [],
    modifiers: [],
    constructorCode: [],
    functions: [],
  };

  nodes.forEach((node) => {
    const block = node.data;
    const params = block.parameterValues || {};

    switch (block.type) {
      case 'erc20-base':
        result.imports.add('@openzeppelin/contracts/token/ERC20/ERC20.sol');
        result.inheritance.add('ERC20');
        result.constructorCode.push(
          `ERC20("${params.name || 'MyToken'}", "${params.symbol || 'MTK'}")`
        );
        result.functions.push(`
    constructor() ${result.constructorCode.length > 0 ? result.constructorCode.join(', ') : ''} {
        _mint(msg.sender, ${params.initialSupply || '1000000'} * 10 ** ${params.decimals || 18});
    }`);
        break;

      case 'erc20-mintable':
        result.imports.add('@openzeppelin/contracts/access/Ownable.sol');
        result.inheritance.add('Ownable');
        const maxSupply = params.maxSupply || '0';
        result.stateVariables.push(`    uint256 public maxSupply = ${maxSupply};`);
        result.functions.push(`
    function mint(address to, uint256 amount) public onlyOwner {
        require(maxSupply == 0 || totalSupply() + amount <= maxSupply, "Max supply exceeded");
        _mint(to, amount);
    }`);
        break;

      case 'erc20-burnable':
        result.imports.add('@openzeppelin/contracts/token/ERC20/extensions/ERC20Burnable.sol');
        result.inheritance.add('ERC20Burnable');
        break;

      case 'erc20-pausable':
        result.imports.add('@openzeppelin/contracts/token/ERC20/extensions/ERC20Pausable.sol');
        result.imports.add('@openzeppelin/contracts/access/Ownable.sol');
        result.inheritance.add('ERC20Pausable');
        result.inheritance.add('Ownable');
        result.functions.push(`
    function pause() public onlyOwner {
        _pause();
    }

    function unpause() public onlyOwner {
        _unpause();
    }`);
        break;

      case 'erc721-base':
        result.imports.add('@openzeppelin/contracts/token/ERC721/ERC721.sol');
        result.imports.add('@openzeppelin/contracts/token/ERC721/extensions/ERC721URIStorage.sol');
        result.imports.add('@openzeppelin/contracts/access/Ownable.sol');
        result.inheritance.add('ERC721');
        result.inheritance.add('ERC721URIStorage');
        result.inheritance.add('Ownable');
        result.stateVariables.push(`    uint256 private _nextTokenId;`);
        result.stateVariables.push(`    uint256 public maxSupply = ${params.maxSupply || '10000'};`);
        result.stateVariables.push(`    string private _baseTokenURI = "${params.baseURI || ''}";`);
        result.constructorCode.push(
          `ERC721("${params.name || 'MyNFT'}", "${params.symbol || 'NFT'}")`
        );
        result.constructorCode.push('Ownable(msg.sender)');
        result.functions.push(`
    function _baseURI() internal view override returns (string memory) {
        return _baseTokenURI;
    }

    function safeMint(address to) public onlyOwner {
        require(_nextTokenId < maxSupply, "Max supply reached");
        uint256 tokenId = _nextTokenId++;
        _safeMint(to, tokenId);
    }

    function tokenURI(uint256 tokenId) public view override(ERC721, ERC721URIStorage) returns (string memory) {
        return super.tokenURI(tokenId);
    }

    function supportsInterface(bytes4 interfaceId) public view override(ERC721, ERC721URIStorage) returns (bool) {
        return super.supportsInterface(interfaceId);
    }`);
        break;

      case 'erc1155-base':
        result.imports.add('@openzeppelin/contracts/token/ERC1155/ERC1155.sol');
        result.imports.add('@openzeppelin/contracts/access/Ownable.sol');
        result.inheritance.add('ERC1155');
        result.inheritance.add('Ownable');
        result.constructorCode.push(`ERC1155("${params.uri || ''}")`);
        result.constructorCode.push('Ownable(msg.sender)');
        result.functions.push(`
    function mint(address account, uint256 id, uint256 amount, bytes memory data) public onlyOwner {
        _mint(account, id, amount, data);
    }

    function mintBatch(address to, uint256[] memory ids, uint256[] memory amounts, bytes memory data) public onlyOwner {
        _mintBatch(to, ids, amounts, data);
    }

    function setURI(string memory newuri) public onlyOwner {
        _setURI(newuri);
    }`);
        break;

      case 'access-ownable':
        result.imports.add('@openzeppelin/contracts/access/Ownable.sol');
        result.inheritance.add('Ownable');
        if (!result.constructorCode.includes('Ownable(msg.sender)')) {
          result.constructorCode.push('Ownable(msg.sender)');
        }
        break;

      case 'access-roles':
        result.imports.add('@openzeppelin/contracts/access/AccessControl.sol');
        result.inheritance.add('AccessControl');
        result.stateVariables.push(`    bytes32 public constant MINTER_ROLE = keccak256("MINTER_ROLE");`);
        result.stateVariables.push(`    bytes32 public constant ADMIN_ROLE = keccak256("ADMIN_ROLE");`);
        result.constructorCode.push('_grantRole(DEFAULT_ADMIN_ROLE, msg.sender)');
        break;

      case 'defi-staking':
        result.imports.add('@openzeppelin/contracts/token/ERC20/IERC20.sol');
        result.imports.add('@openzeppelin/contracts/security/ReentrancyGuard.sol');
        result.imports.add('@openzeppelin/contracts/access/Ownable.sol');
        result.inheritance.add('ReentrancyGuard');
        result.inheritance.add('Ownable');
        result.stateVariables.push(`    IERC20 public stakingToken;`);
        result.stateVariables.push(`    IERC20 public rewardToken;`);
        result.stateVariables.push(`    uint256 public rewardRate = ${params.rewardRate || '100000000000000'};`);
        result.stateVariables.push(`    uint256 public lastUpdateTime;`);
        result.stateVariables.push(`    uint256 public rewardPerTokenStored;`);
        result.stateVariables.push(`    mapping(address => uint256) public userRewardPerTokenPaid;`);
        result.stateVariables.push(`    mapping(address => uint256) public rewards;`);
        result.stateVariables.push(`    mapping(address => uint256) public balances;`);
        result.stateVariables.push(`    uint256 public totalSupply;`);
        result.constructorCode.push('Ownable(msg.sender)');
        result.functions.push(`
    function stake(uint256 amount) external nonReentrant updateReward(msg.sender) {
        require(amount > 0, "Cannot stake 0");
        totalSupply += amount;
        balances[msg.sender] += amount;
        stakingToken.transferFrom(msg.sender, address(this), amount);
    }

    function withdraw(uint256 amount) external nonReentrant updateReward(msg.sender) {
        require(amount > 0, "Cannot withdraw 0");
        totalSupply -= amount;
        balances[msg.sender] -= amount;
        stakingToken.transfer(msg.sender, amount);
    }

    function getReward() external nonReentrant updateReward(msg.sender) {
        uint256 reward = rewards[msg.sender];
        if (reward > 0) {
            rewards[msg.sender] = 0;
            rewardToken.transfer(msg.sender, reward);
        }
    }

    modifier updateReward(address account) {
        rewardPerTokenStored = rewardPerToken();
        lastUpdateTime = block.timestamp;
        if (account != address(0)) {
            rewards[account] = earned(account);
            userRewardPerTokenPaid[account] = rewardPerTokenStored;
        }
        _;
    }

    function rewardPerToken() public view returns (uint256) {
        if (totalSupply == 0) return rewardPerTokenStored;
        return rewardPerTokenStored + (((block.timestamp - lastUpdateTime) * rewardRate * 1e18) / totalSupply);
    }

    function earned(address account) public view returns (uint256) {
        return ((balances[account] * (rewardPerToken() - userRewardPerTokenPaid[account])) / 1e18) + rewards[account];
    }`);
        break;

      case 'utility-reentrancy':
        result.imports.add('@openzeppelin/contracts/security/ReentrancyGuard.sol');
        result.inheritance.add('ReentrancyGuard');
        break;

      case 'utility-withdraw':
        result.imports.add('@openzeppelin/contracts/token/ERC20/IERC20.sol');
        result.functions.push(`
    function withdraw() external onlyOwner {
        uint256 balance = address(this).balance;
        require(balance > 0, "No balance");
        payable(owner()).transfer(balance);
    }

    function withdrawToken(address token) external onlyOwner {
        uint256 balance = IERC20(token).balanceOf(address(this));
        require(balance > 0, "No balance");
        IERC20(token).transfer(owner(), balance);
    }`);
        break;

      case 'utility-whitelist':
        result.stateVariables.push(`    mapping(address => bool) public whitelist;`);
        result.modifiers.push(`    modifier onlyWhitelisted() {
        require(whitelist[msg.sender], "Not whitelisted");
        _;
    }`);
        result.functions.push(`
    function addToWhitelist(address account) external onlyOwner {
        whitelist[account] = true;
    }

    function removeFromWhitelist(address account) external onlyOwner {
        whitelist[account] = false;
    }

    function addBatchToWhitelist(address[] calldata accounts) external onlyOwner {
        for (uint256 i = 0; i < accounts.length; i++) {
            whitelist[accounts[i]] = true;
        }
    }`);
        break;

      case 'governance-voting':
        result.stateVariables.push(`    uint256 public votingPeriod = ${params.votingPeriod || '45818'};`);
        result.stateVariables.push(`    uint256 public quorumPercentage = ${params.quorum || '4'};`);
        result.stateVariables.push(`    uint256 public proposalCount;`);
        result.functions.push(`
    struct Proposal {
        uint256 id;
        string description;
        uint256 forVotes;
        uint256 againstVotes;
        uint256 startBlock;
        uint256 endBlock;
        bool executed;
    }

    mapping(uint256 => Proposal) public proposals;
    mapping(uint256 => mapping(address => bool)) public hasVoted;

    function propose(string memory description) external returns (uint256) {
        uint256 proposalId = proposalCount++;
        Proposal storage proposal = proposals[proposalId];
        proposal.id = proposalId;
        proposal.description = description;
        proposal.startBlock = block.number;
        proposal.endBlock = block.number + votingPeriod;
        return proposalId;
    }

    function vote(uint256 proposalId, bool support) external {
        Proposal storage proposal = proposals[proposalId];
        require(block.number <= proposal.endBlock, "Voting ended");
        require(!hasVoted[proposalId][msg.sender], "Already voted");

        hasVoted[proposalId][msg.sender] = true;
        if (support) {
            proposal.forVotes++;
        } else {
            proposal.againstVotes++;
        }
    }`);
        break;

      default:
        // Handle unknown block types gracefully
        break;
    }
  });

  return result;
}

function generateSecurityReport(nodes: ContractNode[]): SecurityReport {
  const issues: SecurityReport['issues'] = [];
  const passedChecks: string[] = [];

  // Check for common security patterns
  const hasOwnable = nodes.some((n) => n.data.type === 'access-ownable' || n.data.type === 'access-roles');
  const hasReentrancyGuard = nodes.some((n) => n.data.type === 'utility-reentrancy');
  const hasPausable = nodes.some((n) => n.data.type === 'erc20-pausable');
  const hasStaking = nodes.some((n) => n.data.type === 'defi-staking');

  if (hasOwnable) {
    passedChecks.push('Access control implemented');
  } else {
    issues.push({
      severity: 'medium',
      title: 'No Access Control',
      description: 'Contract lacks access control mechanisms',
      recommendation: 'Add Ownable or Role-Based Access control block',
    });
  }

  if (hasReentrancyGuard || !hasStaking) {
    passedChecks.push('Reentrancy protection checked');
  } else if (hasStaking && !hasReentrancyGuard) {
    passedChecks.push('ReentrancyGuard included in staking');
  }

  if (hasPausable) {
    passedChecks.push('Emergency pause mechanism available');
  }

  passedChecks.push('Using OpenZeppelin audited contracts');
  passedChecks.push('Solidity version 0.8.20+ (overflow protection)');
  passedChecks.push('SPDX license identifier included');

  // Calculate score
  const baseScore = 100;
  const deductions = issues.reduce((acc, issue) => {
    switch (issue.severity) {
      case 'critical': return acc + 30;
      case 'high': return acc + 20;
      case 'medium': return acc + 10;
      case 'low': return acc + 5;
      default: return acc;
    }
  }, 0);

  return {
    score: Math.max(0, baseScore - deductions),
    issues,
    recommendations: issues.map((i) => i.recommendation),
    passedChecks,
  };
}

function generateGasEstimates(nodes: ContractNode[]): GasEstimates {
  const deployment = nodes.reduce((acc, node) => acc + (node.data.gasEstimate || 100000), 0);

  const functions: Record<string, number> = {};
  nodes.forEach((node) => {
    if (node.data.type.includes('mint')) {
      functions['mint'] = 50000;
    }
    if (node.data.type.includes('transfer')) {
      functions['transfer'] = 45000;
    }
    if (node.data.type.includes('stake')) {
      functions['stake'] = 80000;
      functions['withdraw'] = 70000;
      functions['getReward'] = 60000;
    }
  });

  // Estimate cost at 30 gwei, $2500 ETH
  const costInUSD = (deployment * 30 * 2500) / 1e9;

  return {
    deployment,
    functions,
    totalEstimate: deployment,
    costInUSD,
  };
}

export async function generateContract(
  nodes: ContractNode[],
  projectName: string
): Promise<GeneratedContract> {
  // Simulate compilation delay
  await new Promise((resolve) => setTimeout(resolve, 1500));

  const contractName = projectName.replace(/[^a-zA-Z0-9]/g, '');
  const processed = processBlocks(nodes);

  // Build imports section
  const importsSection = Array.from(processed.imports)
    .map((imp) => `import "${imp}";`)
    .join('\n');

  // Build inheritance
  const inheritanceSection = processed.inheritance.size > 0
    ? `is ${Array.from(processed.inheritance).join(', ')}`
    : '';

  // Build constructor
  let constructorSection = '';
  if (processed.constructorCode.length > 0) {
    const baseConstructors = processed.constructorCode
      .filter(c => !c.startsWith('_'))
      .join(' ');
    const initCode = processed.constructorCode
      .filter(c => c.startsWith('_'))
      .map(c => `        ${c};`)
      .join('\n');

    constructorSection = `    constructor() ${baseConstructors} {${initCode ? '\n' + initCode + '\n    ' : ''}}`;
  }

  // Generate final source code
  let sourceCode = CONTRACT_TEMPLATE
    .replace('{{imports}}', importsSection)
    .replace('{{contractName}}', contractName)
    .replace(/\{\{contractName\}\}/g, contractName)
    .replace('{{inheritance}}', inheritanceSection)
    .replace('{{stateVariables}}', processed.stateVariables.join('\n'))
    .replace('{{events}}', processed.events.join('\n'))
    .replace('{{modifiers}}', processed.modifiers.join('\n'))
    .replace('{{constructor}}', constructorSection)
    .replace('{{functions}}', processed.functions.join('\n'));

  // Clean up empty lines
  sourceCode = sourceCode
    .replace(/\n{3,}/g, '\n\n')
    .trim();

  // Generate ABI (simplified)
  const abi = generateABI(nodes);

  // Generate security report
  const securityReport = generateSecurityReport(nodes);

  // Generate gas estimates
  const gasEstimates = generateGasEstimates(nodes);

  return {
    id: `contract-${Date.now()}`,
    name: contractName,
    sourceCode,
    abi,
    bytecode: '0x' + '00'.repeat(100), // Placeholder - actual compilation would happen on backend
    constructorArgs: [],
    compiler: {
      version: '0.8.20',
      optimizer: {
        enabled: true,
        runs: 200,
      },
    },
    securityReport,
    gasEstimates,
  };
}

function generateABI(nodes: ContractNode[]): object[] {
  const abi: object[] = [];

  nodes.forEach((node) => {
    switch (node.data.type) {
      case 'erc20-base':
        abi.push(
          { type: 'function', name: 'name', inputs: [], outputs: [{ type: 'string' }], stateMutability: 'view' },
          { type: 'function', name: 'symbol', inputs: [], outputs: [{ type: 'string' }], stateMutability: 'view' },
          { type: 'function', name: 'decimals', inputs: [], outputs: [{ type: 'uint8' }], stateMutability: 'view' },
          { type: 'function', name: 'totalSupply', inputs: [], outputs: [{ type: 'uint256' }], stateMutability: 'view' },
          { type: 'function', name: 'balanceOf', inputs: [{ name: 'account', type: 'address' }], outputs: [{ type: 'uint256' }], stateMutability: 'view' },
          { type: 'function', name: 'transfer', inputs: [{ name: 'to', type: 'address' }, { name: 'amount', type: 'uint256' }], outputs: [{ type: 'bool' }], stateMutability: 'nonpayable' },
          { type: 'function', name: 'approve', inputs: [{ name: 'spender', type: 'address' }, { name: 'amount', type: 'uint256' }], outputs: [{ type: 'bool' }], stateMutability: 'nonpayable' },
          { type: 'event', name: 'Transfer', inputs: [{ name: 'from', type: 'address', indexed: true }, { name: 'to', type: 'address', indexed: true }, { name: 'value', type: 'uint256' }] }
        );
        break;
      case 'erc20-mintable':
        abi.push(
          { type: 'function', name: 'mint', inputs: [{ name: 'to', type: 'address' }, { name: 'amount', type: 'uint256' }], outputs: [], stateMutability: 'nonpayable' }
        );
        break;
      case 'erc721-base':
        abi.push(
          { type: 'function', name: 'safeMint', inputs: [{ name: 'to', type: 'address' }], outputs: [], stateMutability: 'nonpayable' },
          { type: 'function', name: 'tokenURI', inputs: [{ name: 'tokenId', type: 'uint256' }], outputs: [{ type: 'string' }], stateMutability: 'view' }
        );
        break;
    }
  });

  return abi;
}
